import {addDays,dateInWarsaw,dayOf,mondayOf,occurrencesForWeek,selectRelease,type Occurrence} from './schedule';
import {parseFilters,serializeFilters,filterOccurrences,type ScheduleFilterState} from './filters';
import {days,rooms,levels,audiences} from './labels';
import type {Content} from '../content/repository';
const data=JSON.parse(document.querySelector('#schedule-data')!.textContent!) as Content;
const form=document.querySelector<HTMLFormElement>('#filters')!;
const result=document.querySelector('#schedule-results')!;
const dialog=document.querySelector<HTMLDialogElement>('#session-dialog')!;
const name=(slug:string,kind:'disciplines'|'coaches')=>data[kind].find(x=>x.slug===slug)?.name??slug;
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,cls?:string)=>{const x=document.createElement(tag);if(text)x.textContent=text;if(cls)x.className=cls;return x;};
const format=(d:string)=>new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00Z'));
const group=(s:Occurrence['effective'])=>[s.ageMin!==null?`${s.ageMin}${s.ageMax===null?'+':`–${s.ageMax}`} lat`:audiences[s.audience],s.level?levels[s.level]:''].filter(Boolean).join(' · ');
let filters:ScheduleFilterState={};let week='';let selectedWeek=false;let selectedDay=false;let date=dateInWarsaw(new Date());
function loadUrl(){filters=parseFilters(new URLSearchParams(location.search));if(filters.discipline&&!data.disciplines.some(x=>x.slug===filters.discipline))delete filters.discipline;if(filters.coach&&!data.coaches.some(x=>x.slug===filters.coach))delete filters.coach;selectedWeek=Boolean(filters.week);const day=new URLSearchParams(location.search).get('day');selectedDay=day==='all'||filters.day!==undefined;week=filters.week??mondayOf(date);if(!selectedDay&&matchMedia('(max-width:767px)').matches)filters.day=dayOf(date);sync();render();}
function sync(){for(const field of ['discipline','audience','day','level','age','coach','room'] as const)(form.elements.namedItem(field) as HTMLInputElement).value=filters[field]===undefined?'':String(filters[field]);if(filters.age||filters.level||filters.coach||filters.room)document.querySelector<HTMLDetailsElement>('#advanced')!.open=true;}
function updateUrl(){const params=new URLSearchParams(serializeFilters({...filters,day:selectedDay?filters.day:undefined,week:selectedWeek?week:undefined}));if(selectedDay&&!filters.day)params.set('day','all');const query=params.toString();const url=location.pathname+(query?'?'+query:'');if(url!==location.pathname+location.search)history.pushState(null,'',url);}
function show(o:Occurrence){document.querySelector('#session-date')!.textContent=`${days[dayOf(o.date)-1]} · ${format(o.date)} ${o.date.slice(0,4)}`;document.querySelector('#session-title')!.textContent=name(o.effective.disciplineSlug,'disciplines');const target=document.querySelector('#session-detail')!;target.replaceChildren();const dl=el('dl');for(const [label,value] of [['Początek',o.effective.startTime],['Koniec',o.effective.endTime??'Potwierdź w recepcji'],['Grupa',group(o.effective)],['Trener',name(o.effective.coachSlug,'coaches')],['Sala',rooms[o.effective.room]]])dl.append(el('dt',label),el('dd',value));target.append(dl);if(o.status!=='active'){target.append(el('p',`${o.status==='cancelled'?'Odwołane':'Zmiana jednorazowa'}: ${o.explanation}`,'note'));if(o.status==='changed')target.append(el('p',`Pierwotnie: ${o.original.startTime}, ${rooms[o.original.room]}, ${name(o.original.coachSlug,'coaches')}.`));}dialog.showModal();}
function render(){const items=filterOccurrences(occurrencesForWeek(data.releases,week),filters);result.replaceChildren();document.querySelector('#week-label')!.textContent=`${format(week)} — ${format(addDays(week,6))} ${week.slice(0,4)}`;document.querySelector('#result-count')!.textContent=`Znalezione zajęcia: ${items.length}`;
 const starts=data.releases.map(r=>mondayOf(r.validFrom)).sort();const ends=data.releases.map(r=>r.validTo?mondayOf(r.validTo):'9999-12-31').sort();
 document.querySelector<HTMLButtonElement>('#previous-week')!.disabled=!starts.length||week<=starts[0]!;
 document.querySelector<HTMLButtonElement>('#next-week')!.disabled=!ends.length||week>=ends.at(-1)!;
 const notices=document.querySelector('#schedule-notices')!;notices.replaceChildren();for(const r of data.releases)for(const n of r.notices)if(n.startDate<=addDays(week,6)&&n.endDate>=week)notices.append(el('p',`${n.title}: ${n.message} (${n.startDate}–${n.endDate})`,'note schedule-notice'));
 if(Array.from({length:7},(_,i)=>i+1).some(day=>(!filters.day||filters.day===day)&&selectRelease(data.releases,addDays(week,day-1)).kind!=='active')){const note=el('p','Dla części wybranego okresu nie opublikowano grafiku. ','note');const phone=el('a','Potwierdź zajęcia w recepcji: 604 066 669');phone.href='tel:+48604066669';note.append(phone);notices.append(note);}
 const grid=el('div',undefined,'schedule-grid'+(filters.day?' single':''));for(let i=1;i<=7;i++){if(filters.day&&filters.day!==i)continue;const d=addDays(week,i-1);const section=el('section',undefined,'schedule-day'+(d===date?' is-today':''));section.append(el('h3',`${days[i-1]} · ${format(d)}`));const list=items.filter(o=>o.date===d);if(!list.length){const state=selectRelease(data.releases,d);section.append(el('p',state.kind==='active'?'Brak zajęć dla tych filtrów.':'Brak opublikowanego grafiku na ten dzień.','empty'));}for(const o of list){const s=o.effective;const button=el('button',undefined,`session-card ${s.level==='intro'?'intro':''} ${o.status}`);button.type='button';button.dataset.session=o.id;const time=el('time',s.startTime);time.dateTime=`${o.date}T${s.startTime}`;button.append(time,el('strong',name(s.disciplineSlug,'disciplines')));const meta=el('div',undefined,'session-meta');meta.append(el('small',group(s)),el('small',`${name(s.coachSlug,'coaches')} · ${rooms[s.room]}`));button.append(meta);if(o.status!=='active')button.append(el('span',o.status==='cancelled'?'Odwołane':'Zmiana jednorazowa','status'));button.addEventListener('click',()=>show(o));section.append(button);}grid.append(section);}result.append(grid);
 renderPrint(items);
}
function renderPrint(items:Occurrence[]){
 const target=document.querySelector('#schedule-print')!;target.replaceChildren(el('h2',document.querySelector('#week-label')!.textContent!));
 const selected=[filters.discipline?name(filters.discipline,'disciplines'):'Wszystkie dyscypliny',filters.day?days[filters.day-1]:'Cały tydzień',filters.audience?audiences[filters.audience as keyof typeof audiences]:'',filters.level?levels[filters.level as keyof typeof levels]:'',filters.age?`Wiek: ${filters.age}`:'',filters.coach?name(filters.coach,'coaches'):'',filters.room?rooms[filters.room as keyof typeof rooms]:''].filter(Boolean);
 target.append(el('p',selected.join(' · ')));
 for(const release of data.releases)if(release.validFrom<=addDays(week,6)&&(!release.validTo||release.validTo>=week))target.append(el('p',`Obowiązywanie grafiku: ${release.validFrom} – ${release.validTo??'do odwołania'}.`));
 const table=el('table');table.append(el('caption','WWFC · Strzykulska 6a · tel. 604 066 669 · czas Europe/Warsaw'));
 const head=el('thead'),header=el('tr');for(const label of ['Data','Godzina','Zajęcia i grupa','Trener / sala','Zmiany']){const th=el('th',label);th.scope='col';header.append(th);}head.append(header);table.append(head);
 const body=el('tbody');for(const o of items){const s=o.effective;const row=el('tr');for(const value of [`${days[dayOf(o.date)-1]} ${o.date}`,s.startTime+(s.endTime?`–${s.endTime}`:''),`${name(s.disciplineSlug,'disciplines')} · ${group(s)}`,`${name(s.coachSlug,'coaches')} · ${rooms[s.room]}`,o.status==='active'?'':`${o.status==='cancelled'?'Odwołane':'Zmiana jednorazowa'}: ${o.explanation}${o.status==='changed'?` (pierwotnie ${o.original.startTime}, ${rooms[o.original.room]}, ${name(o.original.coachSlug,'coaches')})`:''}`])row.append(el('td',value));body.append(row);}table.append(body);target.append(table);
 if(!items.length)target.append(el('p','Brak zajęć dla wybranego okresu i filtrów.'));
 for(const node of document.querySelector('#schedule-notices')!.children)target.append(node.cloneNode(true));
 target.append(el('p','Godziny bez podanego zakończenia oznaczają wyłącznie początek zajęć. Czas trwania potwierdź w recepcji.'));
}
form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('change',e=>{filters={...parseFilters(new URLSearchParams(new FormData(form) as unknown as Record<string,string>))};if((e.target as HTMLInputElement).name==='day')selectedDay=true;updateUrl();render();});
document.querySelector('#reset-filters')!.addEventListener('click',()=>{date=dateInWarsaw(new Date());week=mondayOf(date);selectedWeek=false;selectedDay=false;filters=matchMedia('(max-width:767px)').matches?{day:dayOf(date)}:{};sync();updateUrl();render();});
for(const [id,amount] of [['previous-week',-7],['next-week',7]] as const)document.querySelector('#'+id)!.addEventListener('click',()=>{week=addDays(week,amount);selectedWeek=true;updateUrl();render();});
document.querySelector('#current-week')!.addEventListener('click',()=>{week=mondayOf(date);selectedWeek=false;updateUrl();render();});
document.querySelector('#print-schedule')!.addEventListener('click',()=>window.print());
dialog.querySelector('button')!.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=Array.from(dialog.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]'));const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}});
function tick(){const next=dateInWarsaw(new Date());if(next!==date){date=next;if(!selectedWeek)week=mondayOf(date);if(!selectedDay&&matchMedia('(max-width:767px)').matches)filters.day=dayOf(date);sync();render();}}
window.addEventListener('popstate',loadUrl);setInterval(tick,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
loadUrl();document.documentElement.classList.add('schedule-enhanced');document.querySelector<HTMLElement>('.schedule-app')!.hidden=false;document.querySelector<HTMLElement>('.schedule-fallback')!.hidden=true;
